-- MySQL Script generated by MySQL Workbench
-- Thu Aug  6 16:35:23 2015
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema fightclub
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `fightclub` ;

-- -----------------------------------------------------
-- Schema fightclub
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `fightclub` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `fightclub` ;

-- -----------------------------------------------------
-- Table `fightclub`.`fighter`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fightclub`.`fighter` ;

CREATE TABLE IF NOT EXISTS `fightclub`.`fighter` (
  `id` VARCHAR(255) NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  `last_name` VARCHAR(50) NOT NULL,
  `nickname` VARCHAR(50) NOT NULL,
  `country` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fightclub`.`event`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fightclub`.`event` ;

CREATE TABLE IF NOT EXISTS `fightclub`.`event` (
  `id` VARCHAR(255) NOT NULL,
  `tournament` ENUM('UFC') NOT NULL DEFAULT 'UFC',
  `name` VARCHAR(255) NOT NULL,
  `date` DATETIME NOT NULL,
  `location` VARCHAR(255) NOT NULL,
  `arena` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fightclub`.`fight`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fightclub`.`fight` ;

CREATE TABLE IF NOT EXISTS `fightclub`.`fight` (
  `id` VARCHAR(255) NOT NULL,
  `fighter1` VARCHAR(255) NOT NULL,
  `fighter2` VARCHAR(255) NOT NULL,
  `sequence` BIGINT(11) NOT NULL,
  `status` ENUM('open_to_bet','closed_to_bet','waiting_accounting','closed') NOT NULL DEFAULT 'open_to_bet',
  `event_id` VARCHAR(255) NOT NULL,
  `winner` VARCHAR(255) NULL,
  `finalization` ENUM('ko','tko','decision','submisson') NULL,
  `round` ENUM('1','2','3','4','5') NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_fighter1_idx` (`fighter1` ASC),
  INDEX `fk_fighter2_idx` (`fighter2` ASC),
  INDEX `fk_event_fight_idx` (`event_id` ASC),
  INDEX `fk_winner_fight_idx` (`winner` ASC),
  CONSTRAINT `fk_fighter1`
    FOREIGN KEY (`fighter1`)
    REFERENCES `fightclub`.`fighter` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_fighter2`
    FOREIGN KEY (`fighter2`)
    REFERENCES `fightclub`.`fighter` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_event_fight`
    FOREIGN KEY (`event_id`)
    REFERENCES `fightclub`.`event` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_winner_fight`
    FOREIGN KEY (`winner`)
    REFERENCES `fightclub`.`fighter` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fightclub`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fightclub`.`user` ;

CREATE TABLE IF NOT EXISTS `fightclub`.`user` (
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `money` DECIMAL(15,2) NOT NULL DEFAULT 1000,
  PRIMARY KEY (`email`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fightclub`.`bet`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fightclub`.`bet` ;

CREATE TABLE IF NOT EXISTS `fightclub`.`bet` (
  `id` BIGINT(11) NOT NULL AUTO_INCREMENT,
  `value` DECIMAL(15,2) NOT NULL,
  `finalization` ENUM('ko','tko','decision','submisson') NULL,
  `round` ENUM('1','2','3','4','5') NULL,
  `user_id` VARCHAR(255) NOT NULL,
  `fight_id` VARCHAR(255) NOT NULL,
  `is_closed` TINYINT(1) NOT NULL DEFAULT 0,
  `winner` VARCHAR(255) NULL,
  `is_draw` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `fk_bet_fight_idx` (`fight_id` ASC),
  INDEX `fk_bet_fighter_idx` (`winner` ASC),
  CONSTRAINT `fk_bet_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `fightclub`.`user` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bet_fight`
    FOREIGN KEY (`fight_id`)
    REFERENCES `fightclub`.`fight` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bet_fighter`
    FOREIGN KEY (`winner`)
    REFERENCES `fightclub`.`fighter` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
